export const FOLLOW_POST_LIST_REQUEST = "FOLLOW_POST_LIST_REQUEST";
export const FOLLOW_POST_LIST_SUCCESS = "FOLLOW_POST_LIST_SUCCESS";
export const FOLLOW_POST_LIST_FAIL = "FOLLOW_POST_LIST_FAIL";

export const FOLLOWER_LIST_REQUEST = "FOLLOWER_LIST_REQUEST";
export const FOLLOWER_LIST_SUCCESS = "FOLLOWER_LIST_SUCCESS";
export const FOLLOWER_LIST_FAIL = "FOLLOWER_LIST_FAIL";

export const FOLLOWING_LIST_REQUEST = "FOLLOWING_LIST_REQUEST";
export const FOLLOWING_LIST_SUCCESS = "FOLLOWING_LIST_SUCCESS";
export const FOLLOWING_LIST_FAIL = "FOLLOWING_LIST_FAIL";
